version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
  - dependency-type: indirect

  groups:
    stylelint:
      patterns:
        - "stylelint"
        - "stylelint-*"
        - "postcss-scss"
    postcss:
      patterns:
        - "postcss"
        - "postcss-*"

- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 99
  allow:
  - dependency-type: direct
