name: deploy

on:
  push:
    branches-ignore:
      - "dependabot/**"
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main-pl
      - "!dependabot/**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
           node-version: 16.x

      - name: Install dependencies & build
        run: |
              npm ci
              npm run build
              mkdir ${{ github.workspace }}/_site
              cp -r ${{ github.workspace }}/site/* ${{ github.workspace }}/_site/*

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
  
  deploy:
    needs: build

    permissions:
      pages: write      # to deploy to Pages
      id-token: write   # to verify the deployment originates from an appropriate source

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
